### ISSUE TITLE
Add example config.yml or spec

### ISSUE THREAD

**Issue by acrisci** [vijayaraj210/dash#1]
I'd like to run it, but I don't know how to make a config.yml file. Can you provide an example?

**Comment by vijayaraj210** [comment]
- Here is a sample [config,.yml](https://github.com/vijayaraj210/dash/blob/master/sample-base/config-sample.yml) to pull metrics from a elasticsearch node.
- On starting a **run**,  Dash would poll source **elastic1** every 2 sec, write to a json dump
- On stopping the **run**, Dash would parse the json dump according to the **categories** and produce graphs using d3.js
